import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Robotik Mühendisliği Projeleri",
  description: "Generated by create next app",
  icons: {
    icon: "/arduino-logo.ico",
    shortcut: "/arduino-logo.ico",
    apple: "/arduino-logo.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <style>{`
          body { font-family: 'Segoe UI', sans-serif; background-color: #f4f7f6; color: #333; margin: 0; padding: 0; line-height: 1.6; min-height: 100vh; display: flex; flex-direction: column; }
          header { background-color: #0078d7; color: white; padding: 40px 20px; text-align: center; box-shadow: 0 4px 10px rgba(0,0,0,0.1); position: relative; }
          .header-name { margin: 0; font-size: 2.8em; font-weight: 900; }
          .header-sub { font-size: 1.2em; opacity: 0.9; margin-top: 10px; }
          .container { max-width: 1000px; margin: 40px auto; padding: 0 20px; flex: 1; }
          .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 30px; }
          .card { background: white; border-radius: 15px; box-shadow: 0 10px 30px rgba(0,0,0,0.1); padding: 30px; text-align: center; cursor: pointer; transition: 0.3s; border-bottom: 5px solid #00979d; }
          .card:hover { transform: translateY(-8px); border-bottom-color: #0078d7; }
          .icon-box { font-size: 4em; margin-bottom: 15px; }
          .detail-view { background: white; padding: 40px; border-radius: 12px; box-shadow: 0 5px 25px rgba(0,0,0,0.15); position: relative; }
          .code-area { background-color: #282c34; color: #abb2bf; padding: 20px; border-radius: 8px; font-family: 'Consolas', monospace; overflow-x: auto; white-space: pre-wrap; margin-top: 15px; font-size: 0.9em; }
          .btn-back { position: absolute; top: 30px; right: 30px; background-color: #333; color: white; border: none; padding: 10px 25px; border-radius: 25px; cursor: pointer; font-weight: bold; }
          .btn-back:hover { background-color: #555; }
          .btn-download { background-color: #0078d7; color: white; padding: 8px 15px; border-radius: 6px; cursor: pointer; border: none; margin-left: 15px; font-weight: bold; }
          
          /* Yeni Mail Butonu */
          .btn-mail { background-color: #007FFF; color: white; padding: 8px 18px; border-radius: 50px; font-weight: bold; cursor: pointer; border: none; transition: 0.3s; box-shadow: 0 4px 10px rgba(0,127,255,0.2); font-size: 0.85em; }
          .btn-mail:hover { background-color: #0066CC; transform: scale(1.05); }
          
          /* E-posta Modal (Overlay) */
          .email-overlay { position: fixed; top: 0; left: 0; width: 100%; height: 100%; background: rgba(0,0,0,0.7); display: flex; justify-content: center; align-items: center; z-index: 1000; }
          .email-modal-box { background: white; padding: 30px; border-radius: 20px; width: 90%; max-width: 400px; text-align: center; box-shadow: 0 10px 40px rgba(0,0,0,0.5); }
          .email-modal-box h2 { margin-top: 0; color: #333; font-size: 1.2em; }
          .email-modal-input { width: 100%; padding: 12px; border-radius: 10px; border: 1px solid #ddd; margin: 15px 0; outline: none; box-sizing: border-box; }
          .email-modal-buttons { display: flex; gap: 10px; }
          .btn-modal-send { background-color: #007FFF; color: white; border: none; padding: 12px; border-radius: 10px; cursor: pointer; font-weight: bold; flex: 2; }
          .btn-modal-cancel { background-color: #eee; color: #333; border: none; padding: 12px; border-radius: 10px; cursor: pointer; flex: 1; }

          /* Hesap ve Form Elemanları */
          .btn-account { background-color: #4CAF50; color: #ffffff; border: none; padding: 15px 40px; border-radius: 100px; font-weight: bold; cursor: pointer; transition: 0.3s; margin-left: 10px; font-size: 1.1em; box-shadow: 0 4px 15px rgba(76,175,80,0.3); }
          .btn-account:hover { background-color: #45a049; transform: translateY(-2px); }
          
          .header-content { display: flex; justify-content: space-between; align-items: center; max-width: 1200px; margin: 0 auto; }

          .btn-save { background-color: #008a00; color: #fff; border: none; padding: 15px 40px; border-radius: 100px; font-weight: bold; cursor: pointer; flex: 1; font-size: 1em; }
          .btn-logout { background-color: #ff0000; color: #fff; border: none; padding: 15px 40px; border-radius: 100px; font-weight: bold; cursor: pointer; flex: 1; font-size: 1em; }
          .form-group { display: flex; flex-direction: column; gap: 8px; }
          .form-label { font-weight: bold; color: #555; }
          .form-flex-row { display: flex; gap: 15px; margin-top: 10px; }
          
          /* Modern Login Ekranı */
          .login-container { display: flex; align-items: center; justify-content: center; min-height: 100vh; background-color: #f4f7f6; }
          .login-card { background: white; padding: 40px; border-radius: 15px; box-shadow: 0 10px 30px rgba(0,0,0,0.1); width: 100%; max-width: 400px; text-align: center; }
          .login-input { width: 100%; padding: 12px 15px; margin: 10px 0; border: 1px solid #ddd; border-radius: 8px; font-size: 1em; box-sizing: border-box; }
          .btn-login { width: 100%; background-color: #0078d7; color: white; border: none; padding: 12px; border-radius: 8px; font-weight: bold; cursor: pointer; margin-top: 20px; transition: 0.3s; }
          .btn-login:hover { background-color: #005a9e; }
          
          .btn-social { width: 100%; background-color: white; padding: 12px; border-radius: 10px; font-weight: 600; cursor: pointer; margin-top: 10px; display: flex; align-items: center; justify-content: center; gap: 12px; transition: all 0.3s ease; border: 1px solid #e0e0e0; font-size: 0.95em; }
          .btn-social:hover { transform: translateY(-2px); box-shadow: 0 4px 12px rgba(0,0,0,0.08); background-color: #ffffff; }
          .btn-social img { filter: drop-shadow(0 1px 1px rgba(0,0,0,0.1)); }
          
          /* Marka Renkleri ve Hover Efektleri */
          .btn-google { border-color: #ea4335; color: #ea4335; }
          .btn-google:hover { background-color: #fff8f7; border-color: #ea4335; }
          .btn-github { border-color: #24292e; color: #24292e; }
          .btn-github:hover { background-color: #f6f8fa; }
          .btn-x { border-color: #000000; color: #000000; }
          .btn-x:hover { background-color: #f2f2f2; }
          .btn-facebook { border-color: #1877F2; color: #1877F2; }
          .btn-facebook:hover { background-color: #f0f7ff; }
          .btn-yahoo { border-color: #6001d2; color: #6001d2; }
          .btn-yahoo:hover { background-color: #f9f4ff; }
          .btn-facebook { border-color: #1877F2; color: #1877F2; }
          .btn-facebook:hover { background-color: #f0f7ff; }
          .btn-facebook img { filter: none; } /* Facebook logosu zaten renkli */
          .btn-yahoo { border-color: #6001d2; color: #6001d2; }
          .btn-yahoo:hover { background-color: #f9f4ff; }
          .btn-yahoo img { filter: none; } /* Yahoo logosu zaten renkli */

          .google-login-separator { margin: 15px 0; position: relative; text-align: center; }
          .google-login-separator::before { content: ""; position: absolute; top: 50%; left: 0; width: 40%; border-top: 1px solid #ddd; }
          .google-login-separator::after { content: ""; position: absolute; top: 50%; right: 0; width: 40%; border-top: 1px solid #ddd; }
          .google-login-separator span { color: #888; font-size: 0.85em; background: white; padding: 0 10px; }

          .password-wrapper { position: relative; }
          .toggle-password { position: absolute; right: 10px; top: 50%; transform: translateY(-50%); background: none; border: none; cursor: pointer; font-size: 1.2em; }
          .remember-me-container { display: flex; align-items: center; gap: 8px; margin-top: 15px; text-align: left; }
          .forgot-password { display: block; margin-top: 15px; color: #0078d7; cursor: pointer; font-size: 0.9em; }
          .error-message { color: #ff0000; margin-top: 15px; font-size: 0.9em; }

          /* Seri Monitör Stilleri */
          .serial-monitor { background: white; border-radius: 15px; display: flex; flex-direction: column; height: 750px; box-shadow: 0 10px 30px rgba(0,0,0,0.1); overflow-y: auto; }
          .serial-header { padding: 15px 20px; background: #f8f9fa; border-bottom: 1px solid #eee; display: flex; justify-content: space-between; align-items: center; }
          .serial-header-left { display: flex; alignItems: center; gap: 15px; }
          .serial-header h2 { margin: 0; }
          .btn-back-static { position: static !important; }
          .serial-output { flex: 1; padding: 15px; font-family: 'Consolas', monospace; font-size: 13px; overflow-y: auto; white-space: pre-wrap; background: #fff; color: #333; border: none; outline: none; resize: none; }
          .serial-footer { padding: 15px 20px; background: #f8f9fa; border-top: 1px solid #eee; display: flex; align-items: center; gap: 15px; flex-wrap: wrap; }
          .serial-footer-controls { display: flex; align-items: center; gap: 8px; }
          .baud-label { font-size: 14px; font-weight: bold; }
          .btn-clear { margin-left: auto; background-color: #666 !important; }
          .btn-connect { background-color: #00ff00; color: #000; border: none; padding: 8px 25px; border-radius: 100px; font-weight: bold; cursor: pointer; transition: 0.3s; }
          .btn-disconnect { background-color: #ff0000; color: #fff; border: none; padding: 8px 25px; border-radius: 100px; font-weight: bold; cursor: pointer; transition: 0.3s; }
          .baud-select { padding: 5px 10px; border-radius: 8px; border: 1px solid #ddd; outline: none; font-size: 14px; }
          .card-serial { border-bottom-color: #ffcc00 !important; }
          
          /* Komut Gönderme Alanı */
          .command-area { padding: 10px 20px; background: #fff; border-bottom: 1px solid #eee; display: flex; gap: 10px; }
          .command-input { flex: 1; padding: 8px 12px; border: 1px solid #ddd; border-radius: 6px; outline: none; }
          .btn-send { background-color: #0078d7; color: white; border: none; padding: 8px 20px; border-radius: 6px; cursor: pointer; font-weight: bold; }

          /* Detay Görünümü Ekleri */
          .mt-30 { margin-top: 30px; }
          .code-area-light { background-color: #f8f9fa; color: #333; border: 1px solid #ddd; }

          /* Seri Monitör Tetikleyici */
          .serial-trigger-container { display: flex; justify-content: center; margin-bottom: 20px; }
          .btn-serial-trigger { background: white; border: 2px solid #ffcc00; border-radius: 10px; padding: 10px; cursor: pointer; display: flex; flex-direction: column; align-items: center; width: 80px; transition: 0.3s; }
          .btn-serial-trigger:hover { background: #fffdf0; transform: scale(1.05); }
          .btn-serial-trigger .icon { font-size: 24px; }
          .btn-serial-trigger span { font-size: 10px; font-weight: bold; margin-top: 4px; color: #555; }

          .format-bar { padding: 10px 20px; background: #eee; display: flex; align-items: center; gap: 10px; font-size: 12px; font-weight: bold; }
          .btn-fmt { background: white; border: 1px solid #ccc; padding: 4px 10px; border-radius: 4px; cursor: pointer; font-size: 11px; }
          .btn-fmt:hover { background: #0078d7; color: white; border-color: #0078d7; }
        `}</style>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        {children}
      </body>
    </html>
  );
}
